spring:
    profiles:
        active: dev # 기본적으로 dev 프로파일 활성화
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
    data:
        redis:
            timeout: 60000
jwt:
    secret: ${JWT_SECRET:mysecretkey123456789012345678901234}
    expiration: 43200000
    refresh-expiration: 604800000 # 7 days