spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cbt?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect # Specify dialect for MySQL
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: cbt-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trust.packages: "*"
        spring.json.value.default.type: "com.example.cbt.kafka.dto.ExamGradedEvent"
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
jwt:
  secret: ${JWT_SECRET:mysecretkey123456789012345678901234}
  expiration: 43200000
logging:
  level:
    org.hibernate.SQL: debug